updated the README.md file
SumoLogic/sumologic-public-partner-apps pull request #15
Opened 2021-05-05 11:44 UTC by avia0

# PR Details

## Description

## Related Issue

## Checklist

- [ ] Changes follows the best practices from the given [docs](https://docs.google.com/document/d/1xfYfruru0RFWOH23GRrRzosSlepJUTcakLFHLHdpEtc/edit?usp=sharing).
- [ ] Updated CHANGELOG.md.
- [ ] Ran unit tests locally.
- [ ] Updated screenshots/sample logs if any.

2021-05-06 15:56 UTC, himanshu219 requested changes

2021-05-06 15:56 UTC, himanshu219 commented on README.md
> +# Installation
Instead of Installation I think it should be Collect Logs for Nucleon

2021-05-06 15:56 UTC, himanshu219 commented on README.md
> +# Dashboard
Instead of Dashboards it should be Install the Cybereason App and View the Dashboards

2021-05-06 15:56 UTC, himanshu219 commented on README.md
> +# Dashboard
After the title we can have below lines

```
This page has instructions for installing the Sumo Logic App for Nucleon and descriptions of each of the app dashboards.

Use the instruction from this doc (https://help.sumologic.com/05Search/Library/Apps-in-Sumo-Logic/Install-Apps-from-the-Library) to install the Nucleon App.
```

And then we can continue with dashboard name and other description.

2021-05-06 15:56 UTC, himanshu219 commented on README.md
> -# sumologic-public-partner-apps
We need to update the manifest.json https://github.com/SumoLogic/sumologic-public-partner-apps/blob/master/Nucleon/Nucleon.manifest.json#L9

and update the helpURL field to https://github.com/SumoLogic/sumologic-public-partner-apps/tree/master/Nucleon

2021-05-07 09:11 UTC, sumo-apps-team approved these changes
Will fix Readme updates in other PR. Merging it for 7th May Release Train.

2021-05-07 09:11 UTC, merged