Mimecast 10082021
SumoLogic/sumologic-public-partner-apps pull request #24
Opened 2021-08-10 19:46 UTC by jason-miller0

# PR Details

## Description

## Related Issue

## Checklist

- [ ] Changes follows the best practices from the given [docs](https://docs.google.com/document/d/1xfYfruru0RFWOH23GRrRzosSlepJUTcakLFHLHdpEtc/edit?usp=sharing).
- [ ] Updated CHANGELOG.md.
- [ ] Ran unit tests locally.
- [ ] Updated screenshots/sample logs if any.

2021-08-11 15:14 UTC, sumo-drew commented
@jason-miller0 - Please fill out the "Documentation" section in the README.md file in the Mimecast folder according to the doc template here - https://docs.google.com/document/d/1Ae9nG--GXo0nkdCNMZIRZIuhCXwJyHvvAwe2Upc6kRo/edit.

For the "Collect Logs for Mimecast" section, you can just refer to our documentation as we have a built-in source to collect the logs, documented here - https://help.sumologic.com/03Send-Data/Sources/02Sources-for-Hosted-Collectors/Cloud-to-Cloud_Integration_Framework/Mimecast_Source

2021-08-16 05:52 UTC, himanshu219 requested changes
Apart from screenshots please add sample logs file and app icon.

2021-08-16 05:52 UTC, himanshu219 commented on Mimecast/README.md
> +# Documentation
Need to update readme

2021-09-02 03:26 UTC, himanshu219 commented
@jason-miller0 the screenshots should be for full dashboard and can you please also provide some sample logs so we can test on our end

2021-09-02 08:40 UTC, jason-miller0 commented on Mimecast/README.md
> +# Documentation
Done

2021-09-02 08:41 UTC, jason-miller0 commented
> @jason-miller0 - Please fill out the "Documentation" section in the README.md file in the Mimecast folder according to the doc template here - https://docs.google.com/document/d/1Ae9nG--GXo0nkdCNMZIRZIuhCXwJyHvvAwe2Upc6kRo/edit.
> 
> For the "Collect Logs for Mimecast" section, you can just refer to our documentation as we have a built-in source to collect the logs, documented here - https://help.sumologic.com/03Send-Data/Sources/02Sources-for-Hosted-Collectors/Cloud-to-Cloud_Integration_Framework/Mimecast_Source
> 
> You can also check out the other partner folders as an example, thanks!



> Apart from screenshots please add sample logs file and app icon so that we can test the app.

Will add sample logs

2021-09-03 10:41 UTC, jason-miller0 commented
> @jason-miller0 the screenshots should be for full dashboard and can you please also provide some sample logs so we can test on our end

Full dashboard screenshots provided

2021-09-03 12:07 UTC, jason-miller0 commented
> > @jason-miller0 - Please fill out the "Documentation" section in the README.md file in the Mimecast folder according to the doc template here - https://docs.google.com/document/d/1Ae9nG--GXo0nkdCNMZIRZIuhCXwJyHvvAwe2Upc6kRo/edit.
> > For the "Collect Logs for Mimecast" section, you can just refer to our documentation as we have a built-in source to collect the logs, documented here - https://help.sumologic.com/03Send-Data/Sources/02Sources-for-Hosted-Collectors/Cloud-to-Cloud_Integration_Framework/Mimecast_Source
> > You can also check out the other partner folders as an example, thanks!
> 
> > Apart from screenshots please add sample logs file and app icon so that we can test the app.
> 
> Will add sample logs

Sample logs have been added.

2021-09-03 19:11 UTC, sumo-apps-team approved these changes

2021-09-03 19:11 UTC, merged